version: "3.8"
services:
    nginx:
        build:   ./nginx
        restart: always
        networks:
            - front
        depends_on:
            - web
            - pgbouncer
    web:
        expose:
            - 80
        networks:
            - app
            - front
        tty: true
        stdin_open: true
        depends_on:
            - pgbouncer

    pgbouncer:
        image: pgbouncer/pgbouncer
        restart: always
        expose:
            - 6432
        networks:
            - db
            - app
            - front
        depends_on:
            - postgres

    postgres:
        image: postgres:13-alpine
        restart: always
        networks:
            - db
networks:
    db:
    app:
    front:
